server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:4444/shopping_cart
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        # убрать символы-разделители из имени circuitbreaker
        alphanumeric-ids:
          enabled: true

management:
  health.circuitbreakers.enabled: true
  endpoint.health.show-details: always

resilience4j.circuitbreaker:
  instances:
    #<feignClientClassName><calledMethod><parameterTypes>
    WarehouseClientcheckProductQuantitiesShoppingCartDto:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      minimumNumberOfCalls: 1
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      springframework:
        orm:
          jpa: INFO