spring:
  datasource:
    url: jdbc:postgresql://localhost:3333/AnalyzerDB
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group-id: analyzer.snapshots
  topic:
    hub-events-topic: telemetry.hubs.v1
    sensor-snapshots-topic: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext