spring:
  datasource:
    url: jdbc:postgresql://localhost:3333/AnalyzerDB
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      springframework:
        orm:
          jpa: INFO

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    hubs-consumer-group-id: analyzer.hubs
    snapshots-consumer-group-id: analyzer.snapshots
  topic:
    hub-events-topic: telemetry.hubs.v1
    sensor-snapshots-topic: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext