spring:
  datasource:
    url: jdbc:postgresql://localhost:4444/CommerceDB
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      springframework:
        orm:
          jpa: INFO